default: &default
  adapter: postgresql
  encoding: utf8
  database: online_shop
  host: localhost
  pool: 5
  username: user_for_shop
  password: password

development:
  <<: *default
  database: online_shop

test:
  <<: *default
  database: spalah_test

production:
  <<: *default
  database: online_shop
