default: &default
  adapter: mysql2
  encoding: utf8
  database: online_shop
  username: root
  password:

development:
  <<: *default
  database: online_shop

test:
  <<: *default
  database: spalah_test

production:
  <<: *default
  database: online_shop
